#pragma once

// Profiling
#ifdef P2PN_PROFILING
#include <easy/profiler.h>

#define P2PNP_BLOCK(text, color) EASY_BLOCK(text, profiler::colors:: color)
#define P2PNP_END_BLOCK EASY_END_BLOCK
#define P2PNP_FUNCTION(color) EASY_FUNCTION(profiler::colors:: color)
#define P2PNP_THREAD(name) EASY_THREAD(name)
#else
#define P2PNP2PNP_BLOCK(text, color)
#define P2PNP_END_BLOCK
#define P2PNP_FUNCTION(color)
#define P2PNP_THREAD(name)
#endif
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)

// Different color stages
#define P2PNP_COLOR_STAGE_1 50
#define P2PNP_COLOR_STAGE_2 100
#define P2PNP_COLOR_STAGE_3 200
#define P2PNP_COLOR_STAGE_4 300
#define P2PNP_COLOR_STAGE_5 400
#define P2PNP_COLOR_STAGE_6 500
#define P2PNP_COLOR_STAGE_7 600
#define P2PNP_COLOR_STAGE_8 700
#define P2PNP_COLOR_STAGE_9 800
#define P2PNP_COLOR_STAGE_10 900
#define P2PNP_COLOR_STAGE_11 A100 
#define P2PNP_COLOR_STAGE_12 A200 
#define P2PNP_COLOR_STAGE_13 A400 
#define P2PNP_COLOR_STAGE_14 A700 

// Colors for XXX 
#define P2PNP_XXX_COLORBASE Green
#define P2PNP_XXX_COLOR_1  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_1 )
#define P2PNP_XXX_COLOR_2  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_2 )
#define P2PNP_XXX_COLOR_3  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_3 )
#define P2PNP_XXX_COLOR_4  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_4 )
#define P2PNP_XXX_COLOR_5  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_5 )
#define P2PNP_XXX_COLOR_6  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_6 )
#define P2PNP_XXX_COLOR_7  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_7 )
#define P2PNP_XXX_COLOR_8  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_8 )
#define P2PNP_XXX_COLOR_9  CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_9 )
#define P2PNP_XXX_COLOR_10 CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_10)
#define P2PNP_XXX_COLOR_11 CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_11) 
#define P2PNP_XXX_COLOR_12 CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_12) 
#define P2PNP_XXX_COLOR_13 CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_13) 
#define P2PNP_XXX_COLOR_14 CONCAT_SYMBOLS(P2PNP_XXX_COLORBASE , P2PNP_COLOR_STAGE_14) 
